configure.ac: Request at least libusb 1.0.9
tegrarcm needs at least libusb 1.0.9 which introduces libusb_error_name.
Otherwise the build fails with the following linker error:

usb.o: In function `usb_read':
.../tegrarcm/src/usb.c:260: undefined reference to `libusb_error_name'
usb.o: In function `usb_write':
.../tegrarcm/src/usb.c:233: undefined reference to `libusb_error_name'

Signed-off-by: Tobias Klauser <tklauser@distanz.ch>
Signed-off-by: Stephen Warren <swarren@nvidia.com>